### ISSUE TITLE
model data

### ISSUE THREAD

**Issue by garudaonekh** [wikilimo/mobile-pest-identification#5]
Please approve my data request to your email. IP102: Insect Pest Recognition Database
I see no reply for several day now. ou_sokch****@yahoo.com

**Comment by lazyoracle** [comment]
The dateset used here (and linked in the README) is not provided or maintained by us. As such, we do not have any control over giving you access to it and approving your requests. Please contact the website linked for any clarifications.

**Comment by garudaonekh** [comment]
ok, thanks. I got it from the owner github.
